package com.systemdesign.ecommarketplace.sharding.strategies;

import com.systemdesign.ecommarketplace.sharding.ShardingStrategy;

/**
 * Mirrors src/sharding/strategies/hash-sharding.strategy.ts exactly:
 * hash(key) % shardCount, using the djb2 string hash.
 *
 * <p>Oja's userId is a UUID (java.util.UUID.randomUUID(), generated by the
 * app at registration time before any row exists anywhere) - there is no
 * auto-increment sequence to shard by, and a shared sequence would itself be
 * a single point of contention across 3 independent databases. Hashing the
 * UUID string distributes users evenly regardless of when they signed up,
 * unlike range sharding, which would pile every *new* signup onto whichever
 * shard currently owns the top of the range (a "hot" shard).
 *
 * <p>djb2 is not cryptographic - it's chosen because it's simple, fast, and
 * deterministic across processes, which is exactly what's needed here: the
 * same userId must always resolve to the same shard, on every replica,
 * forever (until a deliberate resharding operation, which this demo does
 * not implement).
 *
 * <p>Bit-for-bit port note: the TypeScript version relies on JS's `^`
 * operator coercing both operands to Int32 (wrapping, two's-complement) and
 * then does `hash >>> 0` to reinterpret the final 32-bit pattern as
 * unsigned. Java `int` arithmetic overflows/wraps with the exact same
 * two's-complement semantics as JS's ToInt32 coercion, so the per-character
 * loop below (using Java `int`) produces the identical 32-bit pattern as the
 * JS version; {@link Integer#toUnsignedLong(int)} is the direct equivalent
 * of `>>> 0`.
 */
public class HashShardingStrategy implements ShardingStrategy {

  private final int shardCount;

  public HashShardingStrategy(int shardCount) {
    if (shardCount < 1) {
      throw new IllegalArgumentException("shardCount must be >= 1");
    }
    this.shardCount = shardCount;
  }

  @Override
  public String getName() {
    return "hash";
  }

  @Override
  public int getShardCount() {
    return shardCount;
  }

  @Override
  public int resolveShard(String key) {
    long unsignedHash = Integer.toUnsignedLong(djb2(key));
    return mod(unsignedHash, shardCount);
  }

  @Override
  public int resolveShard(long key) {
    return mod(key, shardCount);
  }

  private int djb2(String input) {
    int hash = 5381;
    for (int i = 0; i < input.length(); i++) {
      hash = (hash * 33) ^ input.charAt(i);
    }
    return hash;
  }

  /** JS's `%` can return negative results for negative operands; normalize, same as the TS mod(). */
  private int mod(long value, int divisor) {
    long remainder = value % divisor;
    if (remainder < 0) {
      remainder += divisor;
    }
    return (int) remainder;
  }
}
