server.port=${PORT:3005}

payment.failure-rate=${PAYMENT_FAILURE_RATE:0.7}
circuit.failure-threshold=${CIRCUIT_FAILURE_THRESHOLD:5}
circuit.reset-ms=${CIRCUIT_RESET_MS:10000}
retry.max-attempts=${MAX_RETRIES:3}
retry.delay-ms=${RETRY_DELAY_MS:200}

springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/docs-json
